import SwiftUI
import ApxyCore

@available(iOS 16.0, macOS 13.0, *)
struct ApxyDebugRuntimeSettingsView: View {
    private enum Field: Hashable {
        case serverURL
        case keyID
        case clientSecret
        case capturedDomains
    }

    @ObservedObject var viewModel: ApxyDebugRuntimeSettingsViewModel

    @Environment(\.colorScheme) private var colorScheme
    @FocusState private var focusedField: Field?
    @State private var isPresentingClearConfirmation = false

    var body: some View {
        let theme = ApxyDebugTheme.palette(for: colorScheme)

        ScrollView {
            VStack(spacing: 16) {
                configurationCard(theme: theme)
                applyAction(theme: theme)
            }
            .frame(maxWidth: 760)
            .padding(ApxyDebugChrome.screenPadding)
            .frame(maxWidth: .infinity)
        }
#if os(iOS)
        .scrollDismissesKeyboard(.interactively)
#endif
        .background(theme.canvas.ignoresSafeArea())
        .navigationTitle("Settings")
        .apxyInlineTitle()
        .tint(theme.accent)
        .apxyNavigationChrome(theme: theme, colorScheme: colorScheme)
        .toolbar {
#if os(iOS)
            ToolbarItem(placement: .topBarTrailing) {
                clearDataToolbarButton(theme: theme)
            }

            ToolbarItemGroup(placement: .keyboard) {
                Spacer()

                Button("Done") {
                    focusedField = nil
                }
            }
#else
            ToolbarItem(placement: .primaryAction) {
                clearDataToolbarButton(theme: theme)
            }
#endif
        }
    }

    private func configurationCard(theme: ApxyDebugThemePalette) -> some View {
        ApxyDebugSurfaceCard(style: .plain) {
            VStack(alignment: .leading, spacing: 18) {
                VStack(alignment: .leading, spacing: 6) {
                    Text("Configure session delivery")
                        .font(.headline)
                        .foregroundStyle(theme.textPrimary)

                    Text("Adjust where traffic goes, which credential signs remote ingest, and which domains are captured.")
                        .font(.subheadline)
                        .foregroundStyle(theme.textSecondary)
                        .fixedSize(horizontal: false, vertical: true)
                }

                ApxyDebugRuntimeSettingsFieldBlock(
                    title: "Server URL",
                    detail: "Leave empty to keep the session local-only, or point it at your APXY desktop instance.",
                    systemImage: "server.rack",
                    tint: .accent
                ) {
                    TextField(
                        "",
                        text: $viewModel.serverURL,
                    )
                    .textFieldStyle(.plain)
                    .foregroundColor(theme.textPrimary)
                    .focused($focusedField, equals: .serverURL)
                    .submitLabel(.next)
                    .onSubmit {
                        focusedField = .keyID
                    }
#if os(iOS)
                    .textInputAutocapitalization(.never)
                    .autocorrectionDisabled()
#endif
                }

                Divider()
                    .overlay(theme.border)

                ApxyDebugRuntimeSettingsFieldBlock(
                    title: "Key ID",
                    detail: "Use the key ID generated by APXY for signed SDK ingest.",
                    systemImage: "key",
                    tint: .accent
                ) {
                    TextField("Paste key id", text: $viewModel.keyID)
                        .textFieldStyle(.plain)
                        .focused($focusedField, equals: .keyID)
                        .submitLabel(.next)
                        .onSubmit {
                            focusedField = .clientSecret
                        }
#if os(iOS)
                        .textInputAutocapitalization(.never)
                        .autocorrectionDisabled()
#endif
                }

                Divider()
                    .overlay(theme.border)

                ApxyDebugRuntimeSettingsFieldBlock(
                    title: "Client Secret",
                    detail: "Stored only for the active session. Leave both credential fields empty to stay local-only.",
                    systemImage: "lock",
                    tint: .warning
                ) {
                    SecureField("Paste client secret", text: $viewModel.clientSecret)
                        .textFieldStyle(.plain)
                        .focused($focusedField, equals: .clientSecret)
                        .submitLabel(.next)
                        .onSubmit {
                            focusedField = .capturedDomains
                        }
#if os(iOS)
                        .textInputAutocapitalization(.never)
                        .autocorrectionDisabled()
#endif
                }

                Divider()
                    .overlay(theme.border)

                ApxyDebugRuntimeSettingsFieldBlock(
                    title: "Captured domains",
                    detail: "Filter capture to specific hosts. Separate values with commas and use `*` for wildcard subdomains.",
                    systemImage: "globe",
                    tint: .success
                ) {
                    TextField("api.example.com, *.example.com", text: $viewModel.capturedDomainsText)
                        .textFieldStyle(.plain)
                        .focused($focusedField, equals: .capturedDomains)
                        .submitLabel(.done)
                        .onSubmit {
                            focusedField = nil
                        }
#if os(iOS)
                        .textInputAutocapitalization(.never)
                        .autocorrectionDisabled()
#endif
                }

                if focusedField != nil {
                    HStack {
                        Spacer()

                        Button("Done") {
                            focusedField = nil
                        }
                        .font(.subheadline.weight(.semibold))
                        .foregroundStyle(theme.accent)
                    }
                }

                if let applyStatus = viewModel.applyStatus, let kind = viewModel.applyStatusKind {
                    ApxyDebugRuntimeSettingsStatusBanner(message: applyStatus, kind: kind)
                }

                if !viewModel.isRuntimeActive {
                    Text("APXY is not running right now. Runtime changes apply once an active debug session exists.")
                        .font(.footnote)
                        .foregroundStyle(theme.textSecondary)
                        .fixedSize(horizontal: false, vertical: true)
                }

                Text("Invalid server URLs fall back to local-only mode without interrupting the rest of the debug session.")
                    .font(.footnote)
                    .foregroundStyle(theme.textSecondary)
                    .fixedSize(horizontal: false, vertical: true)
            }
        }
    }

    private func applyAction(theme: ApxyDebugThemePalette) -> some View {
        Button {
            focusedField = nil
            viewModel.applyChanges()
        } label: {
            HStack(spacing: 12) {
                if viewModel.isApplying {
                    ProgressView()
                        .tint(theme.canvas)
                } else {
                    Image(systemName: "checkmark.circle.fill")
                        .font(.body.weight(.semibold))
                }

                Text(viewModel.applyButtonTitle)
                    .font(.headline)

                Spacer(minLength: 12)

                Text("Session only")
                    .font(.caption.weight(.semibold))
                    .padding(.horizontal, 10)
                    .padding(.vertical, 6)
                    .background(theme.canvas.opacity(0.16), in: Capsule())
            }
            .foregroundStyle(theme.canvas)
            .padding(.horizontal, 16)
            .padding(.vertical, 14)
            .frame(maxWidth: .infinity)
            .background(theme.accent, in: RoundedRectangle(cornerRadius: 14, style: .continuous))
        }
        .buttonStyle(.plain)
        .disabled(viewModel.isApplying || viewModel.isClearingData)
        .opacity(viewModel.isApplying || viewModel.isClearingData ? 0.85 : 1)
    }

    private func clearDataToolbarButton(theme: ApxyDebugThemePalette) -> some View {
        Button(role: .destructive) {
            focusedField = nil
            isPresentingClearConfirmation = true
        } label: {
            if viewModel.isClearingData {
                ProgressView()
                    .tint(theme.error)
            } else {
                Image(systemName: "trash")
                    .foregroundStyle(theme.error)
            }
        }
        .disabled(viewModel.isApplying || viewModel.isClearingData)
        .accessibilityLabel(viewModel.clearButtonTitle)
        .popover(isPresented: $isPresentingClearConfirmation, attachmentAnchor: .rect(.bounds), arrowEdge: .top) {
            clearDataPopover(theme: theme)
        }
    }

    private func clearDataPopover(theme: ApxyDebugThemePalette) -> some View {
        VStack(alignment: .leading, spacing: 16) {
            Text("Clear all debug data?")
                .font(.headline)
                .foregroundStyle(theme.textPrimary)

            Text("This removes all captured requests and sessions stored on this device.")
                .font(.subheadline)
                .foregroundStyle(theme.textSecondary)
                .fixedSize(horizontal: false, vertical: true)

            Button("Clear All Data", role: .destructive) {
                isPresentingClearConfirmation = false
                focusedField = nil
                viewModel.clearAllData()
            }
            .buttonStyle(.borderless)
        }
        .padding(20)
        .frame(width: 280, alignment: .leading)
#if os(iOS)
        .modifier(ApxyDebugPopoverAdaptationModifier())
#endif
    }
}

#if os(iOS)
@available(iOS 16.0, macOS 13.0, *)
private struct ApxyDebugPopoverAdaptationModifier: ViewModifier {
    func body(content: Content) -> some View {
        if #available(iOS 16.4, *) {
            content.presentationCompactAdaptation(.popover)
        } else {
            content
        }
    }
}
#endif

#if DEBUG
@available(iOS 17.0, macOS 14.0, *)
#Preview("Runtime Settings Light iOS") {
    Apxy.stop()
    Apxy.start(options: ApxyOptions(
        remote: .init(
            serverURL: "http://127.0.0.1:8083",
            ingestCredentials: .init(keyID: "sdki_preview", clientSecret: "preview-secret")
        )
    ))

    let viewModel = ApxyDebugRuntimeSettingsViewModel()
    viewModel.serverURL = "http://127.0.0.1:9090"
    viewModel.capturedDomainsText = "api.example.com, *.example.com"
    viewModel.applyStatus = "Applied runtime settings."
    viewModel.applyStatusKind = .success

    return NavigationStack {
        ApxyDebugRuntimeSettingsView(viewModel: viewModel)
    }
    .apxyPreviewScreen(.iOS)
    .preferredColorScheme(.light)
}

@available(iOS 17.0, macOS 14.0, *)
#Preview("Runtime Settings Dark macOS") {
    Apxy.stop()

    let viewModel = ApxyDebugRuntimeSettingsViewModel()
    viewModel.serverURL = ""
    viewModel.capturedDomainsText = "staging.apxy.dev"
    viewModel.applyStatus = "Couldn't apply remote runtime settings. Check the server URL and signed ingest credentials."
    viewModel.applyStatusKind = .error

    return NavigationStack {
        ApxyDebugRuntimeSettingsView(viewModel: viewModel)
    }
    .apxyPreviewScreen(.macOS)
    .preferredColorScheme(.dark)
}
#endif
